# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: companias.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ompanias.proto\x12\tcompanias\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n\x08\x43ompania\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"]\n\x11RespuestaCompania\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12*\n\x08\x63ompania\x18\x02 \x01(\x0b\x32\x13.companias.CompaniaH\x00\x88\x01\x01\x42\x0b\n\t_compania2Q\n\tCompanias\x12\x44\n\rCrearCompania\x12\x13.companias.Compania\x1a\x1c.companias.RespuestaCompania\"\x00\x42\x32\n\x18\x63o.edu.uniandes.misw4406B\x0e\x43ompaniasProtoP\x01\xa2\x02\x03VUEb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'companias_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030co.edu.uniandes.misw4406B\016CompaniasProtoP\001\242\002\003VUE'
  _COMPANIA._serialized_start=63
  _COMPANIA._serialized_end=101
  _RESPUESTACOMPANIA._serialized_start=103
  _RESPUESTACOMPANIA._serialized_end=196
  _COMPANIAS._serialized_start=198
  _COMPANIAS._serialized_end=279
# @@protoc_insertion_point(module_scope)
